name: CI Insights Real Run
on:
  push:
    branches: [ci-insights-real-run]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mergifyio/gha-mergify-ci@v22
        with:
          token: mergify_application_key_EUzzhTNAAL4cMDsL2eFZKWjOcwZ0nnxvx-PbTa1x3wV5Oda31a60oKVJe-IHDE6trK-FLas
          report_path: reports/*.xml
        continue-on-error: true
